version: '3'
services:
  wordpress-example-cicd:
    build: .
    restart: always
    environment:
      DEBUG: 0 # 1 or true for enabled, 0, false or undefined for disabled
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      SITE_URL: http://localhost
      SITE_TITLE: Example wordpress 
      ADMIN_USER: admin
      ADMIN_EMAIL: example@email.com
      ADMIN_PASSWORD: themostsecurepassword
    networks:
      - wordpress
    depends_on:
      - mariadb
    ports:
      - 8080:8080

  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./wordpress_db_data:/var/lib/mysql
    networks:
      - wordpress
    ports:
      - 3306:3306

networks:
  wordpress:
